nodeLinker: node-modules

npmScopes:
  react-native-google-signin:
    npmAlwaysAuth: true
    npmAuthToken: '${NAME-npmtoken}'
    npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-4.5.0-git.20241006.hash-29b7fef.cjs
