export const AllActions = {
  GET_POST_IMAGES: 'GET_POST_IMAGES',
  SET_USER_DETAILS: 'SET_USER_DETAILS',
  SET_AUTH_DETAILS: 'SET_AUTH_DETAILS',
  SET_USERS_LIST: 'SET_USERS_LIST',
  SET_USERPOST_LIST: 'SET_USERPOST_LIST',
};
